version: '3.8'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: development
#    volumes:
#      - ./:/usr/src/app
#    env_file:
#      - .env
#    command: npm run dev
#    ports:
#      - "3000:3000"
#    environment:
#      NODE_ENV: development
#    depends_on:
#      - db
#    networks:
#      - onsen-net
  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - onsen_postgres_volume:/var/lib/postgresql/data
    restart: always
    networks:
      - onsen-net
  adminer:
    image: adminer
    ports:
      - "85:8080"
    restart: always
    networks:
      - onsen-net
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - onsen_redis_volume:/data
    restart: always
    networks:
      - onsen-net
networks:
  onsen-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.229.1.0/24
          gateway: 172.229.1.1
volumes:
  onsen_postgres_volume:
  onsen_redis_volume: