version: '3.8'
volumes:
  onsen_postgres_volume:
services:
  db:
    image: postgres:13.4
    restart: on-failure
    networks:
      - nestjs-net
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - onsen_postgres_volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "5050:8080"
    networks:
      - nestjs-net

networks:
  nestjs-net:
    driver: bridge
