version: '3.8'

services:
  db:
    image: postgres:14.11-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - onsen_postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - onsen-net
  adminer:
    image: adminer
    ports:
      - "85:8080"
    networks:
      - onsen-net
networks:
  onsen-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.225.1.0/24
          gateway: 172.225.1.1
volumes:
  onsen_postgres_volume: